---
title: "Resume"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

## Education
**Master of Environmental Data Science** | June 2022\
Bren School of Environmental Science & Management - University of California, Santa Barbara\
*Capstone:* [The Outdoor Equity App](https://shinyapps.bren.ucsb.edu/oe_app/)

**Bachelors of Arts in Urban & Environmental Policy** | Occidental College | 2013\
*Thesis:* [Opportunities and Barriers for Access to "Good" Food with a Focus on Participation by Low-income Communities](https://www.oxy.edu/sites/default/files/assets/UEP/Comps/2012/2013/Boyajian_Clarissa_All%20Bulk%20Everything.pdf)\
*Honors:* Honors with distinction, cum laude\
*Minor:* Spanish


## Environmental Data Scientist Experience
**Dudek | Urban Forestry Data Scientist | Pasadena, CA | 2022 - present**\
•	Developed reproducible systems for analyzing inventory sustainability metrics, canopy cover analysis and equity, and other urban forestry data as part of Urban Forestry Management Plans for city and county clients. \
•	Created comprehensive, clear, and engaging data visualizations including graphs, charts, and maps.\
•	Reviewed standard details and other technical urban forestry plans and documents. \
•	Authored sections of Urban Forestry Management Plans relating to topics such as municipal tree management practices, canopy cover equity, and climate resilience.\


## Urban Forestry & Program Management Experience
**Koreatown Youth & Community Center | Los Angeles, CA | 2017 - 2021**\

**Environmental Services Manager** | 2019 - 2021\
•	Managed Environmental Services department’s $2 million budget and 20+ field and office staff, including: recruiting, hiring, training, and evaluating.\
•	Directed department’s vision and goals for graffiti removal, clean streets, landscaping, tree planting, tree maintenance, and community engagement teams.\
•	Managed 20+ contracts and grants, including: writing proposals, directing vision and strategy for implementation, completing on-going reporting and tracking, and managing relationships with related funders.\
•	Cultivated and maintained excellent working relationships with other urban forestry nonprofit partners, and city and state agencies.\
  
**Urban Forestry Coordinator** | 2017 - 2019\
•	Supervised team of five tree planting field staff, including: hiring, evaluating, overseeing schedule of staff and trucks, and training in arboriculture best practices.\
•	Created and managed map-based tree database system, resulting in higher quality responses to constituent concerns and questions, reports to funders, and project management.\
•	Assisted with grant applications and management, including: developing new grant projects, calculating greenhouse gas sequestration and reduction, selecting tree species, canvassing for planting locations, and managing 8+ state grants simultaneously.\
•	Managed tree planting and establishment care projects for approx. 1,100 trees planted and 1,300 trees maintained annually, including: tracking, permitting, invoicing, and upholding high level of customer service for residents of Los Angeles.\
•	Participated in Los Angele’s Developing an Urban Forestry Management Plan First Steps project process, including attending monthly meetings, participating in project development brainstorming sessions and discussions, and presenting on Plan-it Geo TreePlotter system.


**TreePeople | Urban Forestry Manager | Los Angeles, CA | 2014 - 2017**\
•	Revived and managed Citizen Forester volunteer training program, successfully implementing new programming and outreach to empower, train, and support volunteer leaders.\
•	Organized and taught monthly Citizen Forester workshops, including: developing and updating curriculum, continuously pursuing outreach opportunities to increase attendance, and delivering engaging and motivating in person trainings.\
•	Mentored 15+ Citizen Forester groups through the process of gathering community support, selecting tree species, obtaining planting permits, fundraising, organizing planting day logistics, and planning tree care maintenance schedule
•	Maintained and built strong working relationships with partner organizations and government agencies.\
•	Managed partnership with City of LA’s nonprofit planting collaborative; grew partnership from an informal one to an official partnership that brought in over $10,000 and planted over 400 trees.\
•	Planned and oversaw volunteer tree planting and care events with 50 + volunteers to plant over 250 trees and care for over 1,500 trees.\
•	Assisted with grant applications, including: calculating greenhouse gas sequestration and reduction, selecting tree species, and canvassing for planting locations.


## Additional Professional Experience

**Good Eggs | Los Angeles, CA | 2014 - 2015**\

**Produce Inventory & Ordering Specialist** | 2015\
Managed purchasing and inventory of produce, developed new inventory and waste/donation tracking systems, created and maintained positive direct relationships with local farmers and produce distributors.

**Operations Team Member: Produce Daily & Receiving Daily Lead, Delivery Driver** | 2014 – 2015\
Worked in small teams to manage receiving, inventory, and quality assurance of produce and non-produce grocery items, packed and delivered groceries, and trained new team members on all aspects of the job.

**Cornerstone Farm & Dairy | Farm Assistant | Vashon Island, WA | 2013 - 2014**\
Assisted with sustainable, small-scale farm tasks including: land conservation, cheese making, canning and preserving, cow milking, chicken slaughter/butchery, vegetable growing and harvesting, Farmers’ Market sales, and greenhouse construction.

**Cafe Luna | Baker | Vashon Island, WA | 2013 - 2014**\
Baked pastries and made salads, soups, pizza, and sandwiches in a single-person kitchen.

**Green Bean Coffee Lounge | Los Angeles, CA | 2009 - 2013**\

**Product Purchasing & Inventory Manager** | 2011 - 2013\
Created new inventory system to manage all purchasing and receiving of food and dry goods, worked with team of five students to oversee all operational aspects of business with 50+ student employees, including: hiring, training, facilitating weekly staff meetings, and coordinating staff feedback.\

**Shift Supervisor** | 2010\
Managed shifts of two to three employees, overseeing all daily shift tasks.\

**Barista** | 2009\
Completed daily shift tasks of customer service, cashier sales, drink making, stocking, and safe food handling.
  
## Skills & Certifications

**Certification:** Certified Arborist, WE-12099A – International Society of Arboriculture, Western Chapter (1/18)\

**Technical:** R Markdown, SalesForce, Plan-it Geo TreePlotter, Davey Resource Group TreeKeeper
