---
title: "Clarissa Boyajian's resume"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
    toc: true
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

Aside
================================================================================



Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> cboyajian@bren.ucsb.edu
- <i class="fa fa-github"></i> [cboyajian.github.io](https://cboyajian.github.io)
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------

- Excellent organizational skills: experienced in management of budgets, contracts, and grants, supervising staff and volunteers, and leading large teams.

- Strong relationship building skills: experienced in developing and maintaining mutually supportive partnerships.

- Excellent qualitative and quantitative research, experience gathering and analyzing data. 

- Adept in R, SalesForce, Microsoft Office and Google suites, Plan-it Geo TreePlotter Database, and Apple and Windows OS. 



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.



Main
================================================================================

Clarissa Boyajian {#title}
--------------------------------------------------------------------------------

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Bren School of Environmental Science and Management, University of California, Santa Barbara

M.S. in Environmental Data Science

Santa Barbara, CA

2022

### Occidental College

B.A. in Urban and Environmental Policy

Los Angeles, CA

2013

Thesis: [Opportunities and Barriers for Access to "Good" Food with a Focus on Participation by Low-income Communities](https://www.oxy.edu/sites/default/files/assets/UEP/Comps/2012/2013/Boyajian_Clarissa_All%20Bulk%20Everything.pdf)


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Environmental Services Manager

Koreatown Youth and Community Center

Los Angeles, CA

2021 - 2019


- Manage Environmental Services department’s $2 million budget.
- Manage department’s 20+ field and office staff, including: funding, recruiting, hiring, training, and evaluating.
- Direct department’s vision and goals for graffiti removal, clean streets, landscaping, tree planting, tree establishment care, and
community engagement teams.
- Manage 20+ contracts and grants, including: writing proposals, directing vision and strategy for implementation, completing on-
going reporting and tracking, and managing relationships with related funders.
- Continued role in cultivating and maintaining excellent working relationships with other urban forestry nonprofit partners
throughout California and nation-wide, and city and state agencies.


### Urban Forestry Coordinator

Koreatown Youth and Community Center

Los Angeles, CA

2019 - 2017


- Supervised team of 5 tree planting field staff, including: hiring, evaluating, overseeing schedule of staff and trucks, and training in arboriculture best practices.
- Created and managed map based tree database system (Plan-it Geo TreePlotter), which allowed the department to better respond to constituent concerns and questions, manage planting projects, report to funders, and plan for future planting projects.
- Assisted with grant applications and management, including: developing new projects, calculating greenhouse gas sequestration and reduction, selecting tree species, canvassing for planting locations, and managing 8+ state grants simultaneously.
- Managed tree planting and establishment care projects for approx. 1,100 trees planted and 1,300 trees maintained annually, including: tracking, permitting, invoicing, and upholding high level of customer service for residents of Los Angeles.
- Cultivated and maintained excellent working relationships with urban forestry nonprofit partners and city and state agencies.
- Participated in Developing an Urban Forestry Management Plan First Steps project process, including attending monthly
meetings, participating in project development discussions, and presenting on Plan-it Geo TreePlotter system.


### Urban Forestry Manager

TreePeople

Los Angeles, CA

2017 - 2015


- Hired to revive and manage TreePeople’s Citizen Forester program. Successfully implemented new programming and outreach to empower, train, and support volunteer leaders through process of planning and implementing tree-planting projects.
- Simultaneously mentor 15+ Citizen Forester groups through the process of gathering community support, selecting tree species, obtaining planting permits, fundraising, organizing planting day logistics, and planning tree care maintenance schedule
- Organized and taught monthly Citizen Forester workshops, including: developing and updating curriculum, continuously pursuing outreach opportunities to increase attendance, and delivering engaging and motivating in person trainings.
- Maintained and built strong working relationships with partner organizations and government agencies.
- Managed TreePeople’s partnership with City Plants; grew partnership from an informal one to an official partnership that
brought in over $10,000 and planted over 400 trees.
- Planned and oversaw volunteer tree planting and care events. Included managing 50+ volunteers, ensuring volunteer safety,
teaching proper tree care and planting techniques, and tracking all work in SalesForce.
- Assisted with grant applications, including: calculating greenhouse gas sequestration and reduction, selecting tree species, and
canvassing for planting locations.


### Produce Inventory and Ordering Specialist

Good Eggs

Los Angeles, CA

2015 - 2014


- Created and maintained positive direct relationships with local farmers and produce distributors.
- Managed purchasing and inventory of produce department including developing tracking systems, processing invoices, overseeing quality control, and giving feedback on website improvements for vendor relations.
- Stocked and stored all goods, creating and implementing FIFO tracking system and waste/donation tracking system.
- Trained new team members on all aspects of the job.



